### ISSUE TITLE
how to map from hidden layer representation to the transformed one

### ISSUE THREAD

**Issue by kingfengji** [andrecosta90/sklearn-autoencoder#1]
Hi there, so the pipline is (sort of )

raw x ------> hidden reprensentaion ----> the Wanted X

what if now I have a hidden representation somewhere, and I wish to map this hidden rep to the wanted X, is there a function call to that? 

I mean, is there a decoder from hidden ---> x

Thanks

**Comment by andrecosta90** [comment]
Yes, something like that:

```
def decoder(self, hr):
    z = self.get_reconstructed_input(hr)
    return z
```

```
def decoder_transform(self,hr):
    new_x = self.da.decoder()
    predict_da = theano.function([],z)
    return predict_da(X)
```
